apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: {{ .Release.Name }}-kv

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    clientID: f7a4385e-e470-4e84-b3e3-a819cb0a9c87
    keyvaultName: KV222
    tenantId: 90dd04ee-72ca-46cd-8662-0d614e24d498

    objects: |
      array:
        - |
          objectName: pgadmin-password
          objectType: secret

        - |
          objectName: pgadmin-username
          objectType: secret        